// <auto-generated />
namespace TddBuddy.SpeedyLocalDb.EF.Example.Audit.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Audit_Init : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Audit_Init));
        
        string IMigrationMetadata.Id
        {
            get { return "201710161421268_Audit_Init"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
