// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TddBuddy.SpeedyLocalDb.EF.Example.Audit.DotNetCore.Context;

namespace TddBuddy.SpeedyLocalDb.EF.Example.Audit.DotNetCore.Migrations
{
    [DbContext(typeof(AuditDbContext))]
    [Migration("20191203190322_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TddBuddy.SpeedyLocalDb.EF.Example.Audit.DotNetCore.Entities.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<System.DateTime>("CreateTimestamp");

                    b.Property<string>("LogDetail");

                    b.Property<string>("System");

                    b.Property<string>("User");

                    b.HasKey("Id");

                    b.ToTable("AuditEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
