// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TddBuddy.SpeedyLocalDb.EF.Example.Audit.DotNetCore.Context;

namespace TddBuddy.SpeedyLocalDb.EF.Example.Audit.DotNetCore.Migrations
{
    [DbContext(typeof(AuditDbContext))]
    [Migration("20200911203040_Added_Schema")]
    partial class Added_Schema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TddBuddy.SpeedyLocalDb.EF.Example.Audit.DotNetCore.Entities.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<System.DateTime>("CreateTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("LogDetail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("System")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Entries","aud");
                });
#pragma warning restore 612, 618
        }
    }
}
